### ISSUE TITLE
Create Colors Pallet

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#13]

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/37758c15-0369-4394-b7d4-352a8d9afb05)

Here is the color pallet. In the first line we have the character's colors, next to that we have both the clear and dark tones of the enemys, and in the bottom there is golds and blues and whites for the maps and so on and a little bit of green for grass.
Some colors/shades may vary or may be added more as artwork is created, but the main focus will be the whites and golds.
