### ISSUE TITLE
Player UI/Inventory

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [FlamingoFiestaStudio/OlympusGoneWild#136]
**Description**

In the UI we  need to have player health.

**Ref/Images**:

![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/f5a275cb-bd93-4b83-9afb-a606cdc5ea9c)

**Comment by 201flaviosilva** [comment]
This issue was closed because the project was archived
