### ISSUE TITLE
Study new items

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [FlamingoFiestaStudio/OlympusGoneWild#147]
**Description**
Take this spike to study new items to be added. Add the items found in the comments below.

**Comment by Goncalo-FP** [comment]
- An item that spawns a companion. Leveling up this item will make it fire more often and deal more damage. 
- Another one could be spawning, from time to time, a cone in front of the player that deals damage to the nearby enemies. Leveling up this item increases the cone and the damage dealt.

**Comment by 201flaviosilva** [comment]
This issue was closed because the project was archived
