### ISSUE TITLE
Player character design

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#16]
https://github.com/FlamingoFiestaStudio/OlympusGoneWild/issues/17

Animations list:

- [x] #18
- [x] #19
- [x] #20
- [ ] #132
- [ ] #21

The character must be design in 2D pixel art, with left and right directions in spritesheet animations for idle, running and shooting

**Comment by Gabriel-Sous-a** [comment]
This issue was closed because the project was archived
