### ISSUE TITLE
Design item choose  menu

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [FlamingoFiestaStudio/OlympusGoneWild#160]
**Description**

When player levels up it can choose up from 2 items.

**Ref/Images**:

![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/fec23b58-b08a-4800-a357-7b1699aa0379)

![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/5071bf42-d749-46e2-881a-375bdf26ccab)

**Comment by 201flaviosilva** [comment]
This issue was closed because the project was archived
