### ISSUE TITLE
Player Attacking

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#19]

**Comment by LeoHabs** [comment]
![AttackingAnimation](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/117355219/735e3c0a-b633-4141-b63d-dfcbf5b2a3f9)

[ApolloAttacking.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13061214/ApolloAttacking.zip)
