### ISSUE TITLE
Start Menu Design

### ISSUE THREAD

**Issue by LeoHabs** [FlamingoFiestaStudio/OlympusGoneWild#3]
Linked: https://github.com/FlamingoFiestaStudio/OlympusGoneWild/issues/2

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/93da0093-0133-49b9-a986-ddc7e2df9004)



[Start.sheet_.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/12840297/Start.sheet_.zip)
