### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#46]

**Comment by rittacy** [comment]
![Walk](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/1ddea80b-ebf9-400d-9ff4-f00439af2f1e)
[Walk_sheets.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/12675372/Walk_sheets.zip)

**Comment by 201flaviosilva** [comment]
Hmm, I think his legs are weird, I think they're too far away. But this is a skeleton 🤷‍♂️ Nice work
