### ISSUE TITLE
Attacking

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#47]

**Comment by rittacy** [comment]
![Attack](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/472df158-0744-4caf-bf86-cbcf0f93b3f9)
[Attack_sheets.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/12675391/Attack_sheets.zip)

**Comment by 201flaviosilva** [comment]
Adoro

**Comment by LeoHabs** [comment]
Muito bom
