### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#49]

**Comment by rittacy** [comment]
![skeldeath](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/061cf594-83bb-4e8c-9f9f-f68f041cb86b)
[Skeleton.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/12674800/Skeleton.zip)

**Comment by LeoHabs** [comment]
Mega job
