### ISSUE TITLE
Projectile design

### ISSUE THREAD

**Issue by LeoHabs** [FlamingoFiestaStudio/OlympusGoneWild#5]

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/9280e338-193c-4ed0-8ad5-4ed6e01b2e1e)



[Ilustracao_Sem_Titulo.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13758542/Ilustracao_Sem_Titulo.zip)

**Comment by Gabriel-Sous-a** [comment]
This issue was closed because the project was archived
