### ISSUE TITLE
Level Design Prototype

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#55]

**Comment by LeoHabs** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/117355219/c50e55d9-a4c4-4de4-b5cd-42cc172f3a40)

**Comment by 201flaviosilva** [comment]
Why 1272px?

**Comment by Adan0k** [comment]
I think because the player height🤓

**Comment by Gabriel-Sous-a** [comment]
This issue was closed because the project was archived
