### ISSUE TITLE
Design Options Tab Menu

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#57]
### Buttons: 
- music volume 
- master volume
- environment volume
- language
- brightness
- resolution (screen size)

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/b072e586-e642-4046-abbc-80bdd2f2cc1c)



[Options_menu_sheet_.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13197941/Options_menu_sheet_.zip)

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/678ba7fe-cc30-4822-b140-c89c7bd908e8)



[Screen_menu_sheet_.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13197943/Screen_menu_sheet_.zip)

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/306692ca-ffb8-427a-89ec-d491700c3675)



[Volume_menu_sheet.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13197944/Volume_menu_sheet.zip)

**Comment by 201flaviosilva** [comment]
Look really nice 👌

**Comment by rittacy** [comment]
As requeted here are the options menus with a **prototype** of a background to have an idea of how it's going to look with a background image and/or the map.




![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/927a70fe-4adf-445b-bdca-814a830a22dd)



![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/58a79841-c7e9-41ae-8926-db8544605405)



![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/8c572759-c427-4f4e-8e26-22e464ff7bfc)

**Comment by LeoHabs** [comment]
É isso msm Ritinha,top
