### ISSUE TITLE
Pause Menu Design

### ISSUE THREAD

**Issue by 201flaviosilva** [FlamingoFiestaStudio/OlympusGoneWild#59]
- Resume;
- Exit;

**Comment by rittacy** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/903499e1-e799-470e-9907-3761344923da)
[Pause_sheet_.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13042809/Pause_sheet_.zip)

**Comment by Adan0k** [comment]
![Image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/42160712/acb87194-5de9-40e2-b6da-6c986fcf5687)
