### ISSUE TITLE
Search music type to be added

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [FlamingoFiestaStudio/OlympusGoneWild#76]
In the comments bellow display the results of this spike in order to be presented to the team to in later date be added in the game. Search for music non-copyrighted that suits the project.

**Comment by Gabriel-Sous-a** [comment]
Please note that all the songs will need to be edited specially the volume

#### Start menu music:

- [thesatyrsdance](https://pixabay.com/music/modern-classical-thesatyrsdance-167125/)
- [ancient-rhythm](https://pixabay.com/music/main-title-ancient-rhythm-119039/)
- [ethnic-east](https://pixabay.com/music/adventure-cinematic-ethnic-east-122752/)

#### Continuous music:

- [vikings](https://pixabay.com/music/main-title-vikings-148012/)
- [anxious-march-full](https://pixabay.com/music/build-up-scenes-anxious-march-full-15523/)
- [titans-clash](https://pixabay.com/music/main-title-titans-clash-151520/)

**Comment by 201flaviosilva** [comment]
My opinion:
- Start Menu: I didn't like any, but if I need to choose: `ancient-rhythm`;
- Continuous: `Titans Clash` || `Epic Action` || `Dragon Castle`;

**Comment by rittacy** [comment]
For the Start menu music I liked the first two: [The Satyrs Dance](https://pixabay.com/music/modern-classical-thesatyrsdance-167125/)  ||  [ancient-rhythm](https://pixabay.com/music/main-title-ancient-rhythm-119039/);

For the Continuous music i liked: [Titans Clash](https://pixabay.com/music/main-title-titans-clash-151520/)  ||  [Epic Action](https://pixabay.com/music/main-title-epic-action-113888/);

I believe the [Dragon Castle](https://soundcloud.com/makai-symphony/dragon-castle) music is absolutely amazing for a boss or intense fight.

**Comment by LeoHabs** [comment]
I like the Greta Sting for the Menu
For the continuous music i think all of them are too intense to be played repeatedly, but as Ritta said, [Dragon Castle](https://soundcloud.com/makai-symphony/dragon-castle) is awesome for boss fights.

As a suggestion  [Daddy_s_Music]https://pixabay.com/users/daddy_s_music-22836301/ has some incredible stuff. If we use any of his stuff we have to email him about it, but only because it is ID protected for his sake. Take a look at his lib if you have time

**Comment by Goncalo-FP** [comment]
- Start Menu: It's not the best, but it's the closest to what you'd expect to see in the game: `ancient-rhythm`;
- 
- Continuous: The instruments in these songs help create an environment that matches the theme of the game.`Ethnic East` || `Epic Action`. These two songs are goods examples of in game music but are too epic to be played repeatedly. However they could fit in a boss fight.

**Comment by Adan0k** [comment]
Well, for menu I doesn't like anyone of this, I think the menu music have to be something with a `harp`(a reference to orpheus),
to the boss: `Dragon Castle` is the better

**Comment by Adan0k** [comment]
[mediterranean village dance](https://pixabay.com/music/folk-mediterranean-village-dance-140626/)
[sana geldin](https://pixabay.com/music/modern-classical-sana-geldim-106818/)
[Emotive Harp Inspiring Delicate Relaxing Warm Music](https://pixabay.com/music/beautiful-plays-emotive-harp-inspiring-delicate-relaxing-warm-music-21519/)

**Comment by Gabriel-Sous-a** [comment]
This issue was closed because the project was archived
