### ISSUE TITLE
Design Leader Board Tab

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [FlamingoFiestaStudio/OlympusGoneWild#79]

**Comment by rittacy** [comment]
![IMG_0633](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/142268767/53cc8fba-2d4c-4d9c-9689-ec5655991775)


[Leaderboard_Sheet_.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13399924/Leaderboard_Sheet_.zip)

[Leaderboard.zip](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/files/13399925/Leaderboard.zip)

**Comment by Gabriel-Sous-a** [comment]
This issue was closed because the project was archived
